# Generated by Django 4.2.4 on 2023-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
